@Sudoku.Api_HostAddress = https://localhost:7272

###

POST {{Sudoku.Api_HostAddress}}/api/players
Accept: application/json

###

GET {{Sudoku.Api_HostAddress}}/api/players/{{$guid}}/games
Accept: application/json

###