using Sudoku.Infrastructure.Services.Solvers;

namespace UnitTests.Infrastructure.Services.Solvers;

/// <summary>
/// 16x16 counterpart to <see cref="UnitTests.Infrastructure.Services.BitwiseSolverEngineTests"/>.
/// Fixtures are flat 256-int grids (row-major, 0 = empty, 1-16 = value) generated by seeding
/// the four diagonal 4x4 boxes and letting <see cref="BitwiseSolverEngine"/> complete the grid,
/// then digging holes while re-verifying <see cref="BitwiseSolverEngine.CountSolutions"/> stays
/// at 1. Each fixture was verified programmatically before being embedded here: <c>Solve</c>
/// reproduces the recorded solution and <c>CountSolutions(cap: 2) == 1</c>.
/// </summary>
public class BitwiseSolverEngineSixteenTests
{
    public static IEnumerable<object[]> UniqueSolutionFixtures =>
    [
        [Puzzle1, Solution1],
        [Puzzle2, Solution2],
        [Puzzle3, Solution3],
    ];

    [Theory]
    [MemberData(nameof(UniqueSolutionFixtures))]
    public void Solve_KnownUniqueSixteenPuzzle_FillsEveryCellWithAValidCompleteGrid(int[] puzzle, int[] solution)
    {
        var grid = (int[])puzzle.Clone();

        var solved = BitwiseSolverEngine.Solve(grid);

        solved.Should().BeTrue();
        grid.Should().OnlyContain(v => v >= 1 && v <= 16);
        IsCompleteValidGrid(grid).Should().BeTrue();
        grid.Should().Equal(solution);
    }

    [Theory]
    [MemberData(nameof(UniqueSolutionFixtures))]
    public void Solve_GivenSixteenClues_KeepsThoseCluesInTheSolution(int[] puzzle, int[] solution)
    {
        var grid = (int[])puzzle.Clone();

        BitwiseSolverEngine.Solve(grid);

        for (var i = 0; i < puzzle.Length; i++)
        {
            if (puzzle[i] != 0)
            {
                grid[i].Should().Be(puzzle[i]);
            }
        }

        solution.Should().NotBeNull();
    }

    [Theory]
    [MemberData(nameof(UniqueSolutionFixtures))]
    public void CountSolutions_UniqueSixteenPuzzle_ReturnsOne(int[] puzzle, int[] solution)
    {
        BitwiseSolverEngine.CountSolutions(puzzle, cap: 2).Should().Be(1);

        solution.Should().NotBeNull();
    }

    [Fact]
    public void Solve_InconsistentSixteenGrid_ReturnsFalse()
    {
        var grid = (int[])InconsistentGrid.Clone();

        BitwiseSolverEngine.Solve(grid).Should().BeFalse();
    }

    [Fact]
    public void CountSolutions_InconsistentSixteenGrid_ReturnsZero()
    {
        BitwiseSolverEngine.CountSolutions(InconsistentGrid, cap: 2).Should().Be(0);
    }

    [Fact]
    public void CountSolutions_UnderConstrainedSixteenPuzzle_ReturnsMoreThanOne()
    {
        BitwiseSolverEngine.CountSolutions(UnderConstrainedGrid, cap: 2).Should().BeGreaterThan(1);
    }

    [Fact]
    public void CountSolutions_DoesNotMutateInputSixteenGrid()
    {
        var grid = (int[])Puzzle1.Clone();
        var snapshot = (int[])grid.Clone();

        BitwiseSolverEngine.CountSolutions(grid, cap: 2);

        grid.Should().Equal(snapshot);
    }

    private static bool IsCompleteValidGrid(int[] grid)
    {
        const int size = 16, boxSize = 4;

        for (var unit = 0; unit < size; unit++)
        {
            var rowSeen = new HashSet<int>();
            var colSeen = new HashSet<int>();
            var boxSeen = new HashSet<int>();

            for (var k = 0; k < size; k++)
            {
                if (!rowSeen.Add(grid[unit * size + k]))
                {
                    return false;
                }

                if (!colSeen.Add(grid[k * size + unit]))
                {
                    return false;
                }

                var boxRow = (unit / boxSize) * boxSize + k / boxSize;
                var boxCol = (unit % boxSize) * boxSize + k % boxSize;
                if (!boxSeen.Add(grid[boxRow * size + boxCol]))
                {
                    return false;
                }
            }
        }

        return true;
    }

    // Fixture 1: 90 empty cells. Verified: Solve reproduces Solution1; CountSolutions == 1.
    private static readonly int[] Solution1 =
    [
        5, 8, 9, 1, 10, 11, 4, 6, 14, 7, 12, 3, 13, 2, 15, 16,
        6, 14, 4, 3, 2, 12, 13, 7, 15, 9, 16, 8, 11, 5, 10, 1,
        13, 15, 12, 10, 3, 14, 5, 16, 1, 2, 11, 4, 9, 6, 7, 8,
        7, 11, 16, 2, 9, 8, 15, 1, 10, 5, 6, 13, 12, 3, 4, 14,
        3, 5, 6, 12, 7, 1, 11, 15, 9, 4, 2, 10, 14, 8, 16, 13,
        2, 7, 13, 16, 8, 9, 14, 10, 12, 6, 3, 5, 1, 4, 11, 15,
        9, 1, 8, 15, 4, 6, 2, 5, 11, 14, 13, 16, 7, 10, 3, 12,
        10, 4, 14, 11, 16, 13, 3, 12, 8, 15, 1, 7, 6, 9, 5, 2,
        14, 3, 11, 7, 12, 15, 16, 8, 6, 13, 10, 2, 5, 1, 9, 4,
        8, 9, 15, 5, 11, 7, 1, 4, 3, 16, 14, 12, 10, 13, 2, 6,
        4, 16, 2, 6, 14, 3, 10, 13, 5, 1, 9, 15, 8, 11, 12, 7,
        1, 12, 10, 13, 5, 2, 6, 9, 7, 8, 4, 11, 16, 15, 14, 3,
        12, 6, 3, 9, 15, 5, 7, 14, 4, 11, 8, 1, 2, 16, 13, 10,
        11, 2, 5, 4, 13, 10, 8, 3, 16, 12, 7, 6, 15, 14, 1, 9,
        15, 10, 1, 14, 6, 16, 12, 2, 13, 3, 5, 9, 4, 7, 8, 11,
        16, 13, 7, 8, 1, 4, 9, 11, 2, 10, 15, 14, 3, 12, 6, 5,
    ];

    private static readonly int[] Puzzle1 =
    [
        5, 8, 0, 1, 10, 11, 4, 0, 0, 0, 12, 3, 13, 2, 15, 0,
        6, 14, 4, 3, 0, 12, 0, 0, 15, 0, 0, 8, 11, 5, 10, 1,
        0, 15, 0, 0, 3, 14, 0, 0, 1, 2, 0, 4, 0, 6, 7, 0,
        7, 11, 0, 0, 9, 8, 0, 1, 0, 5, 6, 13, 12, 3, 4, 0,
        3, 0, 6, 12, 0, 0, 0, 0, 9, 0, 2, 10, 14, 8, 16, 0,
        2, 7, 0, 16, 8, 0, 14, 10, 0, 6, 0, 5, 1, 0, 11, 15,
        9, 0, 0, 0, 4, 6, 0, 5, 11, 0, 13, 16, 7, 0, 3, 0,
        10, 0, 14, 11, 16, 13, 3, 12, 8, 15, 1, 7, 6, 9, 5, 2,
        14, 0, 11, 0, 12, 15, 0, 0, 6, 13, 10, 2, 0, 1, 0, 4,
        0, 0, 15, 5, 11, 7, 1, 4, 0, 16, 0, 12, 10, 13, 2, 6,
        4, 16, 2, 6, 14, 3, 10, 13, 5, 1, 0, 15, 8, 11, 12, 7,
        1, 0, 0, 0, 5, 2, 0, 0, 7, 0, 0, 11, 16, 0, 14, 3,
        12, 6, 3, 0, 15, 0, 0, 0, 4, 0, 8, 0, 2, 16, 13, 0,
        11, 0, 5, 0, 0, 10, 8, 0, 0, 12, 0, 6, 15, 0, 0, 0,
        0, 10, 1, 0, 0, 16, 0, 0, 0, 3, 0, 9, 0, 7, 8, 0,
        16, 13, 7, 8, 1, 0, 0, 11, 2, 0, 15, 14, 3, 12, 6, 5,
    ];

    // Fixture 2: 110 empty cells. Verified: Solve reproduces Solution2; CountSolutions == 1.
    private static readonly int[] Solution2 =
    [
        5, 7, 1, 15, 2, 4, 9, 13, 12, 8, 14, 3, 16, 10, 11, 6,
        3, 10, 12, 8, 11, 5, 1, 14, 15, 9, 6, 16, 4, 13, 2, 7,
        16, 13, 14, 4, 8, 7, 6, 10, 1, 5, 2, 11, 12, 9, 15, 3,
        9, 11, 2, 6, 15, 12, 3, 16, 10, 7, 13, 4, 1, 5, 8, 14,
        11, 15, 9, 14, 6, 16, 12, 1, 4, 10, 3, 5, 13, 2, 7, 8,
        1, 2, 4, 16, 10, 3, 7, 5, 13, 15, 9, 8, 6, 12, 14, 11,
        10, 5, 3, 12, 13, 8, 14, 2, 6, 11, 7, 1, 15, 16, 9, 4,
        8, 6, 13, 7, 9, 11, 15, 4, 14, 12, 16, 2, 5, 3, 10, 1,
        6, 12, 11, 9, 16, 1, 10, 15, 2, 14, 8, 13, 3, 7, 4, 5,
        13, 16, 15, 1, 5, 14, 2, 3, 7, 6, 4, 10, 11, 8, 12, 9,
        14, 4, 7, 3, 12, 13, 8, 6, 11, 1, 5, 9, 10, 15, 16, 2,
        2, 8, 10, 5, 4, 9, 11, 7, 3, 16, 15, 12, 14, 6, 1, 13,
        15, 3, 6, 10, 7, 2, 13, 12, 8, 4, 1, 14, 9, 11, 5, 16,
        12, 1, 8, 13, 14, 10, 5, 9, 16, 3, 11, 7, 2, 4, 6, 15,
        7, 9, 16, 2, 1, 15, 4, 11, 5, 13, 12, 6, 8, 14, 3, 10,
        4, 14, 5, 11, 3, 6, 16, 8, 9, 2, 10, 15, 7, 1, 13, 12,
    ];

    private static readonly int[] Puzzle2 =
    [
        0, 7, 1, 0, 2, 4, 0, 0, 12, 8, 0, 0, 16, 10, 0, 0,
        3, 10, 12, 0, 11, 5, 0, 0, 0, 9, 6, 16, 4, 13, 2, 7,
        16, 13, 0, 4, 8, 7, 6, 10, 0, 5, 2, 0, 12, 9, 0, 3,
        9, 11, 2, 6, 15, 0, 3, 0, 10, 0, 13, 4, 0, 5, 8, 14,
        11, 15, 9, 0, 0, 0, 12, 0, 0, 10, 3, 5, 0, 2, 7, 0,
        1, 0, 0, 0, 10, 0, 7, 5, 13, 0, 0, 8, 6, 0, 0, 11,
        0, 0, 3, 12, 0, 8, 0, 2, 0, 0, 0, 1, 0, 0, 9, 0,
        8, 0, 13, 0, 9, 0, 15, 0, 0, 12, 0, 0, 5, 0, 0, 0,
        0, 0, 11, 9, 16, 1, 0, 15, 2, 0, 8, 13, 0, 7, 0, 0,
        0, 0, 15, 1, 0, 14, 0, 3, 0, 0, 4, 0, 11, 0, 12, 9,
        14, 4, 0, 3, 0, 13, 0, 6, 0, 1, 0, 9, 10, 15, 16, 2,
        2, 8, 10, 5, 0, 9, 11, 7, 3, 0, 0, 12, 0, 6, 0, 0,
        15, 0, 0, 10, 7, 2, 0, 12, 0, 4, 0, 14, 0, 0, 5, 16,
        0, 0, 8, 0, 0, 10, 5, 0, 0, 3, 0, 0, 2, 0, 6, 0,
        0, 9, 16, 2, 1, 15, 0, 11, 0, 13, 0, 0, 0, 0, 3, 10,
        4, 14, 0, 11, 3, 0, 16, 8, 9, 0, 0, 15, 7, 0, 13, 12,
    ];

    // Fixture 3: 130 empty cells. Verified: Solve reproduces Solution3; CountSolutions == 1.
    private static readonly int[] Solution3 =
    [
        14, 1, 7, 12, 2, 6, 10, 8, 13, 4, 3, 11, 5, 9, 15, 16,
        9, 4, 6, 11, 5, 12, 1, 14, 15, 10, 16, 2, 7, 3, 8, 13,
        2, 10, 13, 16, 4, 7, 15, 3, 9, 14, 5, 8, 11, 6, 1, 12,
        15, 3, 5, 8, 11, 16, 9, 13, 1, 7, 6, 12, 10, 4, 2, 14,
        8, 14, 9, 13, 15, 1, 5, 11, 3, 16, 4, 6, 12, 7, 10, 2,
        5, 7, 1, 15, 10, 3, 16, 4, 2, 11, 12, 13, 8, 14, 9, 6,
        6, 12, 11, 4, 14, 13, 2, 7, 5, 8, 10, 9, 16, 1, 3, 15,
        10, 2, 16, 3, 6, 8, 12, 9, 7, 1, 14, 15, 4, 11, 13, 5,
        3, 5, 12, 2, 8, 14, 11, 15, 4, 6, 1, 16, 9, 13, 7, 10,
        7, 11, 14, 1, 3, 10, 13, 16, 8, 15, 9, 5, 6, 2, 12, 4,
        4, 13, 15, 9, 7, 5, 6, 12, 10, 2, 11, 14, 1, 8, 16, 3,
        16, 6, 8, 10, 1, 9, 4, 2, 12, 3, 13, 7, 14, 15, 5, 11,
        13, 15, 10, 5, 16, 11, 3, 6, 14, 9, 8, 1, 2, 12, 4, 7,
        12, 16, 2, 6, 9, 15, 8, 5, 11, 13, 7, 4, 3, 10, 14, 1,
        1, 9, 4, 7, 12, 2, 14, 10, 6, 5, 15, 3, 13, 16, 11, 8,
        11, 8, 3, 14, 13, 4, 7, 1, 16, 12, 2, 10, 15, 5, 6, 9,
    ];

    private static readonly int[] Puzzle3 =
    [
        14, 1, 7, 12, 2, 0, 0, 8, 13, 0, 3, 0, 5, 0, 15, 16,
        9, 0, 0, 0, 5, 12, 0, 0, 0, 0, 0, 2, 7, 3, 0, 13,
        2, 10, 0, 0, 4, 0, 0, 0, 9, 14, 5, 8, 0, 6, 0, 0,
        0, 0, 0, 8, 0, 0, 9, 0, 1, 0, 6, 12, 0, 0, 0, 14,
        0, 0, 9, 13, 15, 0, 5, 11, 0, 0, 0, 6, 12, 0, 0, 2,
        5, 0, 1, 15, 10, 3, 16, 0, 0, 11, 12, 13, 0, 14, 0, 0,
        6, 0, 0, 0, 14, 0, 2, 0, 5, 0, 10, 0, 0, 1, 0, 0,
        10, 0, 16, 0, 0, 0, 12, 9, 7, 1, 0, 0, 0, 0, 0, 5,
        3, 5, 0, 0, 0, 14, 11, 15, 0, 0, 0, 16, 9, 0, 0, 0,
        7, 11, 14, 1, 3, 10, 0, 0, 0, 15, 9, 5, 6, 0, 0, 0,
        0, 0, 0, 0, 7, 5, 6, 0, 10, 2, 11, 0, 0, 8, 16, 0,
        0, 0, 0, 0, 0, 9, 4, 0, 0, 0, 13, 0, 14, 0, 5, 0,
        13, 15, 0, 0, 0, 11, 0, 0, 0, 9, 8, 1, 2, 0, 4, 0,
        0, 16, 0, 0, 9, 0, 8, 5, 0, 13, 0, 4, 0, 0, 0, 1,
        0, 9, 4, 0, 0, 0, 14, 10, 0, 0, 15, 3, 0, 16, 0, 8,
        0, 8, 3, 0, 0, 4, 7, 1, 0, 12, 0, 10, 15, 0, 6, 9,
    ];

    // Deliberately under-constrained: 141 empty cells, admits more than one solution
    // (derived from a unique 130-empty puzzle by clearing further cells until
    // CountSolutions(cap: 2) reported 2).
    private static readonly int[] UnderConstrainedGrid =
    [
        2, 13, 0, 0, 14, 0, 8, 0, 0, 0, 15, 0, 0, 0, 0, 6,
        0, 12, 10, 0, 6, 4, 13, 0, 0, 1, 0, 14, 0, 3, 2, 0,
        6, 14, 8, 9, 0, 7, 0, 0, 0, 3, 13, 11, 0, 15, 0, 0,
        0, 0, 0, 0, 11, 0, 15, 10, 8, 0, 0, 9, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 5, 0, 0, 0, 10, 3, 0, 13, 8, 0, 16,
        0, 0, 3, 0, 13, 0, 2, 1, 0, 0, 8, 0, 11, 12, 15, 0,
        0, 16, 11, 0, 0, 9, 14, 0, 0, 0, 4, 13, 0, 6, 0, 0,
        12, 0, 5, 0, 0, 10, 11, 4, 0, 0, 1, 15, 14, 0, 3, 0,
        0, 6, 0, 15, 0, 0, 0, 0, 5, 11, 0, 0, 12, 0, 0, 7,
        9, 0, 0, 2, 5, 0, 0, 8, 14, 16, 0, 0, 1, 0, 0, 0,
        0, 0, 12, 16, 15, 14, 0, 0, 1, 0, 7, 0, 0, 0, 5, 0,
        0, 0, 0, 5, 12, 0, 10, 0, 0, 13, 2, 0, 4, 9, 0, 0,
        11, 7, 16, 10, 0, 0, 0, 13, 3, 0, 0, 0, 0, 4, 0, 12,
        5, 0, 6, 14, 10, 0, 0, 0, 0, 4, 16, 0, 9, 0, 0, 11,
        0, 1, 2, 12, 4, 11, 0, 7, 0, 9, 0, 0, 0, 0, 16, 0,
        0, 8, 0, 0, 0, 0, 5, 0, 0, 0, 11, 0, 0, 0, 0, 2,
    ];

    // Inconsistent: a duplicate 5 in row 0 (and box 0), so no valid grid can result.
    private static readonly int[] InconsistentGrid =
    [
        5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    ];
}
