@Sudoku.Api_HostAddress = http://localhost:5154

POST {{Sudoku.Api_HostAddress}}/api/players
Accept: application/json

###

GET {{Sudoku.Api_HostAddress}}/api/players/abcd/games
Accept: application/json

###